service: tombakery

image: n4cr/tombakery

servers:
  web:
    hosts:
      - 5.78.74.178
    cmd: gunicorn -b 0.0.0.0:8000 wsgi:app
    options:
      memory: 128m

registry:
  server: ghcr.io
  username: n4cr

  password:
    - KAMAL_REGISTRY_PASSWORD

# env:
#   clear:
#   secret:


volumes:
  - "/media/tombakery-demo:/app/data"

builder:
  arch: amd64
  dockerfile: "./Dockerfile"
  context: "./"
  remote: ssh://root@5.78.74.178

proxy:
  host: tomdemo.semicolon.io
  ssl: true
  forward_headers: true
  app_port: 8000
  healthcheck:
    interval: 3
    path: /health
    timeout: 3